;; Metamod plugins.ini
; AMX Mod X 1.8.2 d

; Windows

win32   addons\amxmodx\dlls\amxmodx_mm.dll
win32   addons\dproto\dlls\dproto.dll
win32   addons\mmtimer\dlls\mmtimer.dll
win32 addons/podbot/podbot_mm.dll

; Linux

linux   addons\amxmodx\dlls\amxmodx_mm_i386.so
linux   addons\dproto\dlls\dproto_i386.so
linux   addons\mmtimer\dlls\mmtimer_i386.so
linux addons/podbot/podbot_mm_i386.so