admin.amxx		; admin base (required for any admin-related)

xredirect.amxx

; Basic
admincmd.amxx		; basic admin console commands
adminslots.amxx

; Menus
menufront.amxx		; front-end for admin menus
plmenu.amxx		; players menu (kick, ban, client cmds.)
mapsmenu.amxx		; maps menu (vote, changelevel)

; Chat / Messages
adminchat.amxx		; console chat commands
adminvote.amxx		; vote commands
statsx.amxx
statscfg.amxx
voteban_rus.amxx
umm.amxx
umm_mapconfig.amxx


sil_kick.amxx
weapons_maxclip.amxx
FITH_REMOVER.amxx
vip_teg.amxx
ad_manager.amxx
; Main plugin
zombie_plague40.amxx
zm_vip.amxx
zp_addon_knife.amxx
zp_ammo_ex.amxx
zp_score.amxx
GHW_Weapon_Replacement.amxx
zp_auto_respawn.amxx
zp_zombie_respawn.amxx
zp_no_survivor_recoil.amxx
zp_hud_hp_cso.amxx
zp_winorlose_round_nemsurv.amxx
ammo_vipadm.amxx
serfing_servers.amxx
; Default zombie classes
reclassic.amxx
refast.amxx
rebig.amxx
rehanter.amxx
reshaman.amxx
azp_class_revenant_4.3V.amxx
azp_class_revenant_ice_4.amxx debug
;zp_class_tesla.amxx
; Other
zp_ammochange.amxx
zp_sub_parachute.amxx
; Human extra
zp_extra_firegrenade.amxx
zp_extra_human_armor.amxx
zp_lasermine_24.amxx
azp_weapon_infiex2.amxx debug
azp_weapon_assault_rifle.amxx
zp_extra_crossbow.amxx
azp_weapon_thompson.amxx
azp_weapon_gatling.amxx
azp_weapon_watergun.amxx
azp_weapon_m134ex.amxx
azp_weapon_pkm.amxx
azp_weapon_mk48.amxx
zp_extra_sniper.amxx
azp_weapon_skull5.amxx
; Zombie extra
zp_extra_bomb.amxx
zp_extra_health.amxx
zp_save.amxx
zp_donate_ap.amxx
stopsay.amxx
amx_hpk.amxx
;zp_stats.amxx
zl_noroundend.amxx
zl_voteboss.amxx
zl_rewardsystem.amxx
zl_spawnsystem.amxx
zl_supplybox.amxx
zl_zombiesystem.amxx
zl_mapchooser.amxx
zl_alienboss.amxx