; Добавление уровней ZP Stats
; "Звание уровня"	"нужное к-во ехп"
"Новичек"			"0" // Начальный уровень !не удалять!
"НубоЗомбик"		"1"
"Зомбик"			"2"
"ПроЗомбик"			"3"
"Слизь"				"4"
"Немезида"			"5"
"Сталкер"			"6"
"Ведьма"		    "7"
"Убица"			    "9"
"Царь"			    "10"

