; This configuration for Map Manager plugin
;
; Mapname			Rating		Min	Max	Week
;				[1-5]		[0-32]	[1-32]	SuMoTuWeThFrSa

; Standart de_
zm_dust2_cso  		5               0       32      SuMoTuWeThFrSa
zm_ice_attack              5               0       32      SuMoTuWeThFrSa
zm_sand_new             5               0       32      SuMoTuWeThFrSa
zm_china_v2          5               0       32      SuMoTuWeThFrSa
zm_gorod_new         5               0       32      SuMoTuWeThFrSa
zm_train_beta3     5               0       32      SuMoTuWeThFrSa
zm2_cbble       5               0       32      SuMoTuWeThFrSa
zm_dust_world        5               0       32      SuMoTuWeThFrSa
zm_inferno         5               0       32      SuMoTuWeThFrSa
zm_fdust2x2        5               0       32      SuMoTuWeThFrSa
zm_ice_attack2      5               0       32      SuMoTuWeThFrSa
zm_dust_winter     5               0       32      SuMoTuWeThFrSa
zm_snowbase        5               0       32      SuMoTuWeThFrSa
zm_cbble_kamp      5               0       32      SuMoTuWeThFrSa
zm_dust2_2x2_fixed    	5               0       32      SuMoTuWeThFrSa
zm_kaozcity   	5               0       32      SuMoTuWeThFrSa
zm_maya       	5               0       32      SuMoTuWeThFrSa
zm_toxic_house2    	5               0       32      SuMoTuWeThFrSa
zm_fun_world_4_final   5               0       32      SuMoTuWeThFrSa
zm_world_rmx_fixed    5               0       32      SuMoTuWeThFrSa
zm_heal_dust2       5               0       32      SuMoTuWeThFrSa
zm_dark_city    5               0       32      SuMoTuWeThFrSa
zm_ceronUA    5               0       32      SuMoTuWeThFrSa
zm_infantry    5               0       32      SuMoTuWeThFrSa
zm_lmn_ice    5               0       32      SuMoTuWeThFrSa
zm_sand       5               0       32      SuMoTuWeThFrSa
zm_assault_anthill    5               0       32      SuMoTuWeThFrSa
zm_vendetta     5               0       32      SuMoTuWeThFrSa
zm_3rooms      5               0       32      SuMoTuWeThFrSa
zm_assault_d3     5               0       32      SuMoTuWeThFrSa
zm_aztec_mini       5               0       32      SuMoTuWeThFrSa
zm_desert_2011     5               0       32      SuMoTuWeThFrSa
zm_snow_volta    5               0       32      SuMoTuWeThFrSa
zm_snowbase2     5               0       32      SuMoTuWeThFrSa
zm_xata      5               0       32      SuMoTuWeThFrSa
zm_zombattack_new   5               0       32      SuMoTuWeThFrSa
zm_zero_blood      5               0       32      SuMoTuWeThFrSa
zm_brambor     5               0       32      SuMoTuWeThFrSa
